### ISSUE TITLE
Support for FreeBSD 13

### ISSUE THREAD

**Issue by ghost** [Aquantia/aqtion-freebsd#1]
Is support for FreeBSD 13-CURRENT in the works? I tried this code with an AQN-108 adapter and encountered the following panic:
```
aq0: <Aquantia AQtion 5Gbit Network Adapter> mem 0xdfc40000-0xdfc4ffff,0xdfc50000-0xdfc50fff,0xdf800000-0xdfbfffff irq 16 at device 0.0 on pci1            
panic: Assertion powerof2(sctx->isc_nrxd_max[i]) failed at /usr/src/sys/net/iflib.c:5292                                                                          
cpuid = 2                                                                        
time = 1562686162                                                                
KDB: stack backtrace:                                                            
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00a274a110   
vpanic() at vpanic+0x19d/frame 0xfffffe00a274a160                                
panic() at panic+0x43/frame 0xfffffe00a274a1c0                                   
iflib_register() at iflib_register+0x347/frame 0xfffffe00a274a200                
iflib_device_register() at iflib_device_register+0xa0/frame 0xfffffe00a274a590   
iflib_device_attach() at iflib_device_attach+0xb7/frame 0xfffffe00a274a5c0       
device_attach() at device_attach+0x3ce/frame 0xfffffe00a274a600                  
device_probe_and_attach() at device_probe_and_attach+0x71/frame 0xfffffe00a274a630                                                                                
pci_driver_added() at pci_driver_added+0xe6/frame 0xfffffe00a274a670             
devclass_driver_added() at devclass_driver_added+0x7a/frame 0xfffffe00a274a6b0   
devclass_add_driver() at devclass_add_driver+0x189/frame 0xfffffe00a274a6f0      
module_register_init() at module_register_init+0xc0/frame 0xfffffe00a274a720     
linker_load_module() at linker_load_module+0xbd8/frame 0xfffffe00a274aa50        
kern_kldload() at kern_kldload+0xef/frame 0xfffffe00a274aaa0                     
sys_kldload() at sys_kldload+0x5b/frame 0xfffffe00a274aad0                       
amd64_syscall() at amd64_syscall+0x276/frame 0xfffffe00a274abf0                  
fast_syscall_common() at fast_syscall_common+0x101/frame 0xfffffe00a274abf0      
--- syscall (304, FreeBSD ELF64, sys_kldload), rip = 0x8002dceea, rsp = 0x7fffffffe528, rbp = 0x7fffffffeaa0 ---                                                  
KDB: enter: panic                                                                
[ thread pid 1130 tid 100175 ]                                                   
Stopped at      kdb_enter+0x3b: movq    $0,kdb_why
```

**Comment by kevlo** [comment]
> Is support for FreeBSD 13-CURRENT in the works? I tried this code with an AQN-108 adapter and encountered the following panic:
> 
> ```
> aq0: <Aquantia AQtion 5Gbit Network Adapter> mem 0xdfc40000-0xdfc4ffff,0xdfc50000-0xdfc50fff,0xdf800000-0xdfbfffff irq 16 at device 0.0 on pci1            
> panic: Assertion powerof2(sctx->isc_nrxd_max[i]) failed at /usr/src/sys/net/iflib.c:5292                                                                          
> cpuid = 2                                                                        
> time = 1562686162                                                                
> KDB: stack backtrace:                                                            
> db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00a274a110   
> vpanic() at vpanic+0x19d/frame 0xfffffe00a274a160                                
> panic() at panic+0x43/frame 0xfffffe00a274a1c0                                   
> iflib_register() at iflib_register+0x347/frame 0xfffffe00a274a200                
> iflib_device_register() at iflib_device_register+0xa0/frame 0xfffffe00a274a590   
> iflib_device_attach() at iflib_device_attach+0xb7/frame 0xfffffe00a274a5c0       
> device_attach() at device_attach+0x3ce/frame 0xfffffe00a274a600                  
> device_probe_and_attach() at device_probe_and_attach+0x71/frame 0xfffffe00a274a630                                                                                
> pci_driver_added() at pci_driver_added+0xe6/frame 0xfffffe00a274a670             
> devclass_driver_added() at devclass_driver_added+0x7a/frame 0xfffffe00a274a6b0   
> devclass_add_driver() at devclass_add_driver+0x189/frame 0xfffffe00a274a6f0      
> module_register_init() at module_register_init+0xc0/frame 0xfffffe00a274a720     
> linker_load_module() at linker_load_module+0xbd8/frame 0xfffffe00a274aa50        
> kern_kldload() at kern_kldload+0xef/frame 0xfffffe00a274aaa0                     
> sys_kldload() at sys_kldload+0x5b/frame 0xfffffe00a274aad0                       
> amd64_syscall() at amd64_syscall+0x276/frame 0xfffffe00a274abf0                  
> fast_syscall_common() at fast_syscall_common+0x101/frame 0xfffffe00a274abf0      
> --- syscall (304, FreeBSD ELF64, sys_kldload), rip = 0x8002dceea, rsp = 0x7fffffffe528, rbp = 0x7fffffffeaa0 ---                                                  
> KDB: enter: panic                                                                
> [ thread pid 1130 tid 100175 ]                                                   
> Stopped at      kdb_enter+0x3b: movq    $0,kdb_why
> ```

On -current, both ntxd and nrxd values should be power of 2.

Here's the diff:
--- aq_hw.h.orig        2019-07-12 14:27:29.977492658 +0800
+++ aq_hw.h     2019-07-12 14:27:37.297532000 +0800
@@ -178,8 +178,8 @@

 #define HW_ATL_B0_MIN_RXD 32U
 #define HW_ATL_B0_MIN_TXD 32U
-#define HW_ATL_B0_MAX_RXD 8184U
-#define HW_ATL_B0_MAX_TXD 8184U
+#define HW_ATL_B0_MAX_RXD 8192U
+#define HW_ATL_B0_MAX_TXD 8192U

 #define HW_ATL_B0_MTU_JUMBO  16352U
 #define HW_ATL_B0_TSO_SIZE (160*1024)

**Comment by cail** [comment]
Thanks, we'll integrate that fix.

**Comment by ghost** [comment]
After making that change I hit another panic due to a lock ordering issue, so there appears to be more work still to be done on the 13-CURRENT front.

**Comment by kevlo** [comment]
> After making that change I hit another panic due to a lock ordering issue, so there appears to be more work still to be done on the 13-CURRENT front.

That locking issue is easily fixed.  There's no need to call iflib_led_create()
in aq_if_attach_pre().   The diff: http://ix.io/1QjQ

**Comment by ghost** [comment]
Do you by any chance have working code already? 😅 Commenting that line out just exposes another failing assertion.

**Comment by kevlo** [comment]
> Do you by any chance have working code already? sweat_smile Commenting that line out just exposes another failing assertion.

The fail assertion has absolutely nothing to do with commenting                
iflib_led_create().

**Comment by ghost** [comment]
What I meant is that there are still more issues preventing the driver from being functional on 13-CURRENT. I have moved off of that and on to FreeNAS 11.2 for now, where the driver works fine in my testing so far. It would be nice to have it working on FreeBSD 13 and beyond as well, so thank you in advance to anyone working on this :)

**Comment by kevlo** [comment]
> What I meant is that there are still more issues preventing the driver from being functional on 13-CURRENT. I have moved off of that and on to FreeNAS 11.2 for now, where the driver works fine in my testing so far. It would be nice to have it working on FreeBSD 13 and beyond as well, so thank you in advance to anyone working on this in secret ;)


What an attitude!  You asked for help and I helped you solved problems, you didn't say thank you.  Instead, you want someone to fix all problems with an AQN-108 adapter for you, otherwise you'll think she/he is working on this in secret.

**Comment by ghost** [comment]
I am saying thank you. Sorry if that came across as cryptic. I'm not trying to fix the problems with this driver myself, you're right. I'm reporting that it doesn't work on 13-CURRENT and asking if anyone is working on it. Again, thank you to those who are working on it.

**Comment by kevlo** [comment]
I tested an AQC-107 adapter on -CURRENT today, there's an assertion fails.
Here's the diff: http://ix.io/1QJ3

aq works for me :)
$ dmesg |grep aq
aq0: <Aquantia AQtion 10Gbit Network Adapter> mem 0xfeaf0000-0xfeafffff,0xfeaef000-0xfeaeffff,0xfe400000-0xfe7fffff irq 18 at device 0.0 on pci2
aq0: Using 1024 TX descriptors and 1024 RX descriptors
aq0: Using 4 RX queues 4 TX queues
aq0: Using MSI-X interrupts with 5 vectors
aq0: Assign IRQ 0 to rx ring 0
aq0: Assign IRQ 1 to rx ring 1
aq0: Assign IRQ 2 to rx ring 2
aq0: Assign IRQ 3 to rx ring 3
aq0: Assign IRQ 0 to tx ring 0
aq0: Assign IRQ 1 to tx ring 1
aq0: Assign IRQ 2 to tx ring 2
aq0: Assign IRQ 3 to tx ring 3
aq0: Assign IRQ 4 to admin proc
aq0: Ethernet address: 40:b0:76:xx:xx:xx
aq0: netmap queues/slots: TX 4/1024, RX 4/1024

Please let me know if it works for you, thanks.

**Comment by koobs** [comment]
I've just landed the driver (v.0.0.4) in FreeBSD Ports: [freshports: net/aquantia-atlantic-kmod](https://www.freshports.org/net/aquantia-atlantic-kmod/) via [ports r510761](https://svnweb.freebsd.org/changeset/ports/510761)

I am obtaining the sources via this repository

It would be *great* to get any known fixes into this tree via PR's (or directly) here, rather than being delayed snapshots of code from an internal source with unknown update frequency

**Comment by ghost** [comment]
We're hoping to bring this driver in through the port for FreeNAS as well. It would be good to have some signs of life here.

**Comment by logost** [comment]
Thanks all for pointing out to incompatible places.
v0.0.5 works well on 13-CURRENT

**Comment by ghost** [comment]
Excellent news, thank you!

**Comment by koobs** [comment]
@freqlabs Could we add git tags for 0.0.5 version and going forward? This allows downstreams (like me for the FreeBSD kmod port) to checkout the code by tag rather than git hash

**Comment by logost** [comment]
@koobs,   https://github.com/Aquantia/aqtion-freebsd/releases/tag/v0.0.5

**Comment by koobs** [comment]
@logost Thank you :)
