### ISSUE TITLE
Build error under FreeBSD 13

### ISSUE THREAD

**Issue by swuensch** [Aquantia/aqtion-freebsd#17]
Hi everyone,

I provided the following to two patches with their respective pull requests:

**Current master does not compile under FreeBSD-13.0-RELEASE**

- Please find the patch in #19 

```
aq_main.c:800:42: error: incompatible function pointer types passing 'u_int (void *, struct sockaddr_dl *, int)' (aka 'unsigned int (void *, struct sockaddr_dl *, int)') to parameter of type 'iflladdr_cb_t *' (aka 'unsigned int (*)(void *, struct sockaddr_dl *, unsigned int)') [-Werror,-Wincompatible-function-pointer-types]
                if_foreach_llmaddr(iflib_get_ifp(ctx), aq_mc_filter_apply, softc);
                                                       ^~~~~~~~~~~~~~~~~~
/usr/include/net/if_var.h:752:45: note: passing argument to parameter here
u_int if_foreach_llmaddr(if_t, iflladdr_cb_t, void *);
                                            ^
1 error generated.
*** [aq_main.o] Error code 1

make: stopped in /usr/home/sven/src/swuensch-aqtion-freebsd
1 error

```

**Integration of ports tree patch to use arc4random()**

- Please find the patch in #18 

**New tag after successful merges**

- Please create a new tag after successful merges, as the port in the ports tree refers to a specific tag. I will contact the ports maintainer, koobs@FreeBSD.org, to update accordingly.

Cheers
Sven

**Comment by swuensch** [comment]
@cail thank you for merging the two patches into master.

Would you create a new tag as well, please? The maintainer of the ports tree package, koobs@FreeBSD.org (@koobs ?),  can pick it up, then.

Edit: I just noticed that tagging for versions 0.0.4 and 0.0.5 was done by @logost and there is a version string in aq_common.h.

I will close this issue and we can discuss tagging and versioning in a new dedicated issue.

**Comment by cail** [comment]
@swuensch, I can put a tag, but please verify the latest PR works fine for your setup as well.
PS Marvell is not supporting this driver officially now, so I don't have any ability to build/verify the functionality. I can only help with PRs and merges.
