### ISSUE TITLE
pfSense build steps partially working

### ISSUE THREAD

**Issue by therevoman** [Aquantia/aqtion-freebsd#2]
I was trying to build this for pfSense 2.4.4...   took a while because "cc" is not available in FreeBSD 11+.  

Please add a few more notes on building this package.

Here are my "random" steps to get it compiled on a pfSense VM.

##########

Using the guide here 

https://docs.netgate.com/pfsense/en/latest/packages/installing-freebsd-packages.html 

And downloading packages from here 

[](http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/ )

 

curl -L -o FreeBSD-src https://github.com/pfsense/FreeBSD-src/archive/RELENG_2_4_4.zip 

Move contents to /usr/src 

```
# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/binutils-2.32_1,1.txz 

# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/mpfr-4.0.2.txz 

# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/mpc-1.1.0_2.txz 

# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/gcc9-9.2.0.txz 

# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/gcc-9_4.txz 

# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/cc65-2.18.txz 
 
# pkg add http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/gcc9-9.2.0.txz 

```
Somewhere along the way... 

```
# ln -s /usr/src/include/stdbool.h stdbool.h 
# ln -s /usr/src/sys/sys/stdint.h stdint.h 
# ln -s /usr/src/sys/sys/syslog.h syslog.h 
# ln -s /usr/src/sys/sys/unistd.h unistd.h 
# ln -s /usr/src/sys/sys/errno.h errno.h 
 
# make COMPILER_TYPE=clang CC=clang 

# make COMPILER_TYPE=clang CC=clang install 

```

**Comment by ghost** [comment]
Are you trying to build this _on_ pfSense? `cc` is certainly available in FreeBSD 11+ proper.

**Comment by therevoman** [comment]
My apologies. It's true I was building this on pfSense as I don't have a
proper FreeBSD system anymore. While looking for packages to pull over I
read something about gcc being deprecated in FreeBSD 10 and later.

https://www.phoronix.com/scan.php?page=news_item&px=mtewmji
And
http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/

Since pfSense does not ship with compilers installed I manuall added
packages by from : http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/
After installing the gcc package, make threw an unknown flag error.  So I
installed llvm and was off to the races.

I'll post on the netgate forums to see how to properly handle 'cc'.

**Comment by therevoman** [comment]
PfSense is a strange BSD variant
