### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by koobs** [Aquantia/aqtion-freebsd#3]
I recently committed this driver to FreeBSD ports: https://www.freshports.org/net/aquantia-atlantic-kmod/ and note that license (BSD3CLAUSE) information is only mentioned in source headers (which is fine).

It's desirable to also reference and include a license file in the FreeBSD package for this driver, and generally, good (best?) practice to include them in any projects source repositories root, for easy identification.

Could you please include a LICENSE file in this repository, such that we can reference it in the ports, and include it in the package.

**Comment by logost** [comment]
added in v0.0.5
