### ISSUE TITLE
FreeBSD if_atlantic.ko does not bind to 10GBase-T AQC100

### ISSUE THREAD

**Issue by skbooden** [Aquantia/aqtion-freebsd#6]
I purchased Asus XG-C100F to connect Xigmanas (FreeBSD 12.1) to 10Gbe switch. Unfortunately, the if_atlantic.ko driver would not bind to the adapter. Adapter shows up via pciconf as class=0x020000 card=0x874a1043 chip=0x00b11d6a rev=0x02 hdr=0x00. However, from what I can surmise, the chip id 0x00b1 is not recognized by if_atlantic.ko driver. Compiling the driver after a port package pull to FreeBSD 12.1 did not work either. I replaced the ASUS card with a Sonnet Presto Solo 10GBaseT card and if_atlantic.ko driver binded and aq0 is the resulting network device. The Presto card has a chip ID of AQC107S, 0x87b1. I noticed that this id is in aq_main.c, but that 0x00b1 is not. I added a line of code to the Aquantia FreeBSD driver, recompiled, and now the driver binds to the card and it works. I added this line to aq_main.c PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC100, "Aquantia AQtion 10GbitFC Network Adapter") . Everything seems OK now.

[aq_main.c.txt](https://github.com/Aquantia/aqtion-freebsd/files/4477797/aq_main.c.txt)

**Comment by zoon01** [comment]
Some more is missing, please use this:

patch-aqtion__aq_main.c:

+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC107, "Aquantia AQtion 10Gbit Network Adapter"),
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC108, "Aquantia AQtion 5Gbit Network Adapter"),
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC109, "Aquantia AQtion 2.5Gbit Network Adapter"),
++	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC100, "Aquantia AQtion 10Gbit Network Adapter"),
+ 
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC107S, "Aquantia AQtion 10Gbit Network Adapter"),
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC108S, "Aquantia AQtion 5Gbit Network Adapter"),
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC109S, "Aquantia AQtion 2.5Gbit Network Adapter"),
++	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC100S, "Aquantia AQtion 10Gbit Network Adapter"),
+ 
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC111, "Aquantia AQtion 5Gbit Network Adapter"),
+ 	PVID(AQUANTIA_VENDOR_ID, AQ_DEVICE_ID_AQC112, "Aquantia AQtion 2.5Gbit Network Adapter"),

Regards,
zoon01

**Comment by koobs** [comment]
@zoon01 Thank you for the patch. Could you include your change proposal as a PR?

**Comment by phedoreanu** [comment]
Created #10.

**Comment by phedoreanu** [comment]
#10 has been merged. @skbooden I think you can close the issue.

**Comment by swuensch** [comment]
Similar issue for ACQ107, which appears with a device id 0x0001 in QNAP HS-453DX. 

Please find the patch in pull-request #14
